import store from "@/store";

const light = {
  dark: false,
  colors: {
    "login-border": "#1a63e4",
    "login-body-bg": "#ffffff",
    "login-logo": "#333333",
    "login-input-text": "#fff",
    "login-input-bg": "#f9fcff",
    "login-option-text": "#1351dd",
    "login-btn-text": "#ffffff",
    "login-btn-bg": "#0446bc",
    background: "#c7deff", // body bg
    "content-bg": "#fff", // 컨텐츠 영역 백 컬러
    surface: "#FFFFFF",
    primary: "#6200EE",
    "primary-darken-1": "#121212", // basic font color
    "tags-item-bg": "#f9fcff", // tags bg
    "tags-text": "#8ea8ce", // tags text
    "tags-item-border": "#d5e4f3",
    "tags-item-active-bg": "#1a64e4",
    "tags-text-active": "#ffffff",
    "tags-item-active-border": "#d5e4f3",
    "tags-empty-bg": "#f4f4f4",
    "tags-finish-text": "#ffffff",
    "tags-finish-bg": "#1a64e4",
    "tags-finish-disabled-text": "#a6aeb7",
    "tags-finish-disabled-bg": "#f4f4f4",
    sidebar: "#1a64e4", // sidebar bg
    "logo-color": "#fff",
    "avatar-color": "#fff",
    "logout-btn": "#0d46c0",
    "logout-btn-text": "#fff",
    "sidebar-nav-title-color": "#fff",
    "sidebar-nav-item-color": "#fff",
    "sidebar-nav-divider-color": "#3576e7",
    "sidebar-nav-divider-color2": "#3576e7",
    "sidebar-nav-close-btn-bg": "#0d46c0",
    "sidebar-nav-close-btn-text": "#fff",
    "side-active": "#FFFFFF",
    "side-active-item": "#0d46c0",
    "side-active-text": "#1a63e4",
    "side-child-active": "#0d46c0",
    top: "#fff", // top bg
    "top-icon": "#121212",
    profile: "#fff", // profile bg
    "profile-icon": "#121212",
    "theme-color": "#1a64e4",
    "border-color": "#d4e5f7", // "#206ac4",
    "btn-border-color": "#d4e5f7", // "#206ac4",
    "divider-color": "#919191", // 나눔선 color
    popover: "#fff", // popover 메뉴 bg
    "popover-item": "#fff", // popover 메뉴 item bg
    "popover-icon": "#206ac4",
    "popover-font-color": "#206ac4",
    "popover-divider-color": "#e6e7e9",
    breadcrumbs: "#f2f3f7",
    "scrollbar-track": "#fff",
    "scrollbar-thumb": "#c1c1c1",
    "search-item-text": "#333",
    "primary-btn": "#1a64e4",
    "primary-text": "#758ea8",
    "surface-btn": "#ffffff",
    "surface-text": "#7f99b3",
    "custom-first-btn": "#a2c64c",
    "custom-first-text": "#ffffff",
    "custom-second-btn": "#1cb8d0",
    "custom-second-text": "#ffffff",
    "custom-third-btn": "#ffa500",
    "custom-third-text": "#ffffff",
    "primary-form": "#fbfcff",
    "item-bg": "#FFFFFF",
    "grid-header-text": "#395571",
    "grid-border": "#d5e4f3",
    "grid-row-border": "#d5e4f3",
    "grid-header-bg": "#f9fcff",
    "grid-body-bg": "#f9fcff",
    "grid-row-text": "#121212",
    "grid-hover-text": "#ffffff",
    "grid-hover-bg": "#1364e5",
    "grid-active-color": "#0022cd",
    "grid-footer-bg": "#ffffff",
    "grid-footer-disabled-color": "#7f99b3",
    "grid-footer-possible-color": "#1351dd",
    "grid-footer-item-color": "#395571",
    "grid-footer-active-item-bg": "#1a63e4",
    "grid-footer-active-item-color": "#fff",
    "cancel-btn-text": "#666666",
    "cancel-btn-bg": "#ffffff",
    "excute-btn-text": "#ffffff",
    "excute-btn-bg": "#1a63e4",
    "calendar-bg": "#1a63e4",
    "alert-excute-bg": "#1a64e4",
    "alert-excute-text": "#ffffff",
    "alert-cancel-bg": "#ffffff",
    "alert-cancel-text": "#333",
    "alert-card-bg": "#ffffff",
    "alert-card-text": "#333333",
    "dashboard-bg": "#ffffff",
    "dashboard-text": "#121212",
    "404-text": "#333333",
    "mobile-side-top": "#0d46c0",
    "progress-content": "#ffffff",
    "progress-text": "#333",
    "popup-bg": "#ffffff",
    "popup-border": "#ffffff",
    "popup-title": "#333",
    "popup-item-bg": "#FFFFFF",
    "popup-item-border": "#d4e5f7",
    "popup-item-text": "#333",
    "popup-btn-border": "#b9cae2",
    "first-item": "#1a63e4",
    "second-item": "#1a63e4",
    "checker-items": "#fff",
    "mach-header": "#1a63e4",
    "mach-header-text": "#fff",
    "field-box-item-bg": "#FFFFFF",
    "progress-bg": "#1a63e4",
    "progress-empty-bg": "#eeeeee",
    "progress-title": "#2e2e2e",
    "tsorter-bg": "#f9fcff",
    "tsorter-column-item": "#ffffff",
    "tsorter-transportItem-bg": "#ffffff",
    "tsorter-transportItem-border": "#d5e4f3",
    "tsorter-groupSize-border": "#d5e4f3",
    "tsorter-group-mapper-border": "#b7cdee",
    "tsorter-group-mapper-bg": "#c6ddff",
    "tsorter-group-mapper": "#819fcd",
    "tsorter-group-mapper-active-border": "#1659d9",
    "tsorter-group-mapper-active-bg": "#1962e4",
    "tsorter-group-mapper-active": "#ededed",
    "tsorter-trry-text": "#333",
    "tsorter-trry-border": "#d5e4f3",
    "disabled-bg": "#555555"
  }
};

const dark = {
  dark: true,
  colors: {
    "login-border": "#ffbc32",
    "login-body-bg": "#ffffff",
    "login-logo": "#292d33",
    "login-input-text": "#fff",
    "login-input-bg": "#f9fcff",
    "login-option-text": "#1351dd",
    "login-btn-text": "#292d33",
    "login-btn-bg": "#ffbc32",
    background: "#3e444c", // body bg
    "content-bg": "#2b3138", // 컨텐츠 영역 백 컬러
    surface: "#FFFFFF",
    primary: "#6200EE",
    "primary-darken-1": "#333333", // basic font color
    "tags-item-bg": "#232930", // tags bg
    "tags-text": "#666666", // tags text
    "tags-item-border": "#51555b",
    "tags-item-active-bg": "#ffbc32",
    "tags-text-active": "#222222",
    "tags-item-active-border": "#51555b",
    "tags-empty-bg": "#292e36",
    "tags-finish-text": "#ffffff",
    "tags-finish-bg": "#ffbc32",
    "tags-finish-disabled-text": "#717883",
    "tags-finish-disabled-bg": "#232930",
    sidebar: "#ffbc32", // sidebar bg
    "logo-color": "#333333",
    "avatar-color": "#333333",
    "logout-btn": "#2e2e2e",
    "logout-btn-text": "#ffbc32",
    "sidebar-nav-title-color": "#033333",
    "sidebar-nav-item-color": "#033333",
    "sidebar-nav-divider-color": "#e1742c",
    "sidebar-nav-divider-color2": "#ffc44a",
    "sidebar-nav-close-btn-bg": "#2e2e2e",
    "sidebar-nav-close-btn-text": "#ffbc32",
    "side-active": "#2b3138",
    "side-active-item": "#2b3138",
    "side-active-text": "#ffbc32",
    "side-child-active": "#2e2e2e",
    top: "#2a2b36", // top bg
    "top-icon": "#ffffff",
    profile: "#fff", // profile bg
    "profile-icon": "#121212",
    "theme-color": "#ffbc32",
    "border-color": "#51555b",
    "btn-border-color": "#232930",
    "divider-color": "#919191", // 나눔선 color
    popover: "#fff", // popover 메뉴 bg
    "popover-item": "#fff", // popover 메뉴 item bg
    "popover-icon": "#206ac4",
    "popover-font-color": "#206ac4",
    "popover-divider-color": "#e6e7e9",
    breadcrumbs: "#181924",
    "scrollbar-track": "#424242",
    "scrollbar-thumb": "#686868",
    "search-item-text": "#333",
    "primary-btn": "#ffbc32",
    "primary-text": "#333333",
    "surface-btn": "#404348",
    "surface-text": "#ffffff",
    "custom-first-btn": "#a2c64c",
    "custom-first-text": "#ffffff",
    "custom-second-btn": "#1cb8d0",
    "custom-second-text": "#ffffff",
    "custom-third-btn": "#fbceb1",
    "custom-third-text": "#ffffff",
    "primary-form": "#232930",
    "item-bg": "#ffbc32",
    "grid-header-text": "#fff",
    "grid-border": "#51555b",
    "grid-row-border": "#fff",
    "grid-header-bg": "#232930",
    "grid-body-bg": "#3d424a",
    "grid-row-text": "#ededed",
    "grid-hover-text": "#333333",
    "grid-hover-bg": "#ffbd2e",
    "grid-active-color": "#ff8e03",
    "grid-footer-bg": "#2b3138",
    "grid-footer-disabled-color": "#4c535b",
    "grid-footer-possible-color": "#ffbc32",
    "grid-footer-item-color": "#f2c976",
    "grid-footer-active-item-bg": "#ffbc32",
    "grid-footer-active-item-color": "#033333",
    "cancel-btn-text": "#ffffff",
    "cancel-btn-bg": "#2e2e2e",
    "excute-btn-text": "#333333",
    "excute-btn-bg": "#ffbc32",
    "calendar-bg": "#1a63e4",
    "alert-excute-bg": "#ffbc32",
    "alert-excute-text": "#2e2e2e",
    "alert-cancel-bg": "#ffffff",
    "alert-cancel-text": "#333",
    "alert-card-bg": "#2e2e2e",
    "alert-card-text": "#ffbc32",
    "dashboard-bg": "#3d424a",
    "dashboard-text": "#ededed",
    "404-text": "#333333",
    "mobile-side-top": "#ffc44a",
    "progress-content": "#2e2e2e",
    "progress-text": "#ffbc32",
    "popup-bg": "#2e2e2e",
    "popup-border": "#1a1a1a",
    "popup-title": "#ffbc32",
    "popup-item-bg": "#2e2e2e",
    "popup-item-border": "#ffffff",
    "popup-item-text": "#ffffff",
    "popup-btn-border": "#1a1a1a",
    "first-item": "#ffbc32",
    "second-item": "#ffbc32",
    "checker-items": "#2d3239",
    "box-legend": "#ffbc32",
    "checker-items-text": "#6e7176",
    "mach-header": "#ffbc32",
    "mach-header-text": "#000000",
    "field-box-item-bg": "#2d3239",
    "check-left-top-item-border": "#2d3239",
    "checker-wrap-items-border": "#2d3239",
    "progress-bg": "#ffbc32",
    "progress-empty-bg": "#333333",
    "progress-title": "#2e2e2e",
    "tsorter-bg": "#f9fcff",
    "tsorter-column-item": "#ffffff",
    "tsorter-transportItem-bg": "#ffffff",
    "tsorter-transportItem-border": "#d5e4f3",
    "tsorter-groupSize-border": "#d5e4f3",
    "tsorter-group-mapper-border": "#b7cdee",
    "tsorter-group-mapper-bg": "#c6ddff",
    "tsorter-group-mapper": "#819fcd",
    "tsorter-group-mapper-active-border": "#1659d9",
    "tsorter-group-mapper-active-bg": "#1962e4",
    "tsorter-group-mapper-active": "#ededed",
    "tsorter-trry-text": "#333",
    "tsorter-trry-border": "#d5e4f3",
    "disabled-bg": "#555555"
  }
};

const theme = {
  light: light,
  dark: dark
};

// export default store.getters.themeClass === "dark" ? dark : light;
export default theme;
